const SUPABASE_URL="https://mmjsgrdujjomopefkzeq.supabase.co";
const SUPABASE_KEY="sb_publishable__UgjBRf9uxweu8yEFQNvbw_wo10XxZY";
let session=localStorage.getItem('apoyo_session')||''; let me=null;
const $=id=>document.getElementById(id);
async function rpc(fn,body={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${fn}`,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY},body:JSON.stringify(body)});const txt=await r.text();if(!r.ok)throw new Error(txt||`Error ${r.status}`);if(!txt)return null;try{return JSON.parse(txt)}catch{return txt}}
function paymentHTML(id){return `<div class="grid"><label>Método<select id="${id}Metodo"><option value="SPEI">SPEI / Transferencia</option><option value="PayPal">PayPal</option><option value="Efectivo">Efectivo</option></select></label><label>Nombre del titular<input id="${id}Titular" required></label><label id="${id}ClabeWrap">CLABE (18 dígitos)<input id="${id}Clabe" inputmode="numeric" maxlength="18" placeholder="18 dígitos"></label><label id="${id}PaypalWrap" class="hidden">Correo PayPal<input id="${id}Paypal" type="email" placeholder="correo de PayPal"></label></div>`}
$('paymentFields').innerHTML=paymentHTML('s'); $('paymentFields2').innerHTML=paymentHTML('p');
function togglePayment(prefix){const metodo=$(`${prefix}Metodo`).value;const cw=$(`${prefix}ClabeWrap`),pw=$(`${prefix}PaypalWrap`),cl=$(`${prefix}Clabe`),pp=$(`${prefix}Paypal`);cw.classList.toggle('hidden',metodo!=='SPEI');pw.classList.toggle('hidden',metodo!=='PayPal');cl.required=metodo==='SPEI';pp.required=metodo==='PayPal'}
['s','p'].forEach(prefix=>{$(`${prefix}Metodo`).addEventListener('change',()=>togglePayment(prefix));togglePayment(prefix)});
function paymentData(prefix){return {metodo:$(`${prefix}Metodo`).value,titular:$(`${prefix}Titular`).value.trim(),banco:'',clabe:$(`${prefix}Clabe`).value.replace(/\D/g,''),paypal:$(`${prefix}Paypal`).value.trim()}}
function validatePayment(prefix){const d=paymentData(prefix);if(!d.titular)return 'Escribe el nombre del titular.';if(d.metodo==='SPEI'&&d.clabe.length!==18)return 'La CLABE debe tener exactamente 18 dígitos.';if(d.metodo==='PayPal'&&!d.paypal)return 'Escribe el correo de PayPal.';return ''}
function fillPayment(prefix,d={}){if(d.metodo)$(`${prefix}Metodo`).value=d.metodo;$(`${prefix}Titular`).value=d.titular||'';$(`${prefix}Clabe`).value=d.clabe||'';$(`${prefix}Paypal`).value=d.paypal||'';togglePayment(prefix)}
$('loginForm').onsubmit=async e=>{e.preventDefault();$('loginEstado').textContent='Ingresando...';try{const x=await rpc('apoyo_login',{p_numero:Number($('loginNumero').value),p_password:$('loginPassword').value});session=x.token;localStorage.setItem('apoyo_session',session);await init();}catch(err){$('loginEstado').textContent='Número de asesor o contraseña incorrectos.'}};
$('logout').onclick=async()=>{try{await rpc('apoyo_logout',{p_token:session})}catch{}localStorage.removeItem('apoyo_session');location.reload()};
async function init(){if(!session)return;try{me=await rpc('apoyo_me',{p_token:session});$('loginCard').classList.add('hidden');$('panel').classList.remove('hidden');$('bienvenida').textContent=`Asesor ${me.numero}${me.es_admin?' — Administradora':''}`;$('rolTexto').textContent=me.es_admin?'Acceso general de administración':'Aquí puedes responder únicamente tus mensajes asignados.';if(me.primer_ingreso){$('primerIngreso').classList.remove('hidden');$('normalPanel').classList.add('hidden')}else{$('primerIngreso').classList.add('hidden');$('normalPanel').classList.remove('hidden');if(me.es_admin){document.querySelector('[data-admin-tab="asesores"]').classList.remove('hidden');document.querySelector('[data-admin-tab="solicitudes"]').classList.remove('hidden');document.querySelector('[data-admin-tab="todos"]').classList.remove('hidden');document.querySelector('[data-admin-tab="papelera"]').classList.remove('hidden');document.querySelector('[data-admin-tab="estadisticas"]').classList.remove('hidden')}await loadAll()}}catch(e){localStorage.removeItem('apoyo_session');session=''}}
$('setupForm').onsubmit=async e=>{e.preventDefault();if($('newPassword').value!==$('confirmPassword').value){$('setupEstado').textContent='Las contraseñas no coinciden.';return}const pe=validatePayment('s');if(pe){$('setupEstado').textContent=pe;return}try{await rpc('apoyo_configurar_primera_vez',{p_token:session,p_password:$('newPassword').value,p_pago:paymentData('s')});me.primer_ingreso=false;$('setupEstado').textContent='Datos guardados correctamente.';await init()}catch(err){console.error(err);$('setupEstado').textContent='No se pudo guardar. '+(err.message||'Revisa los datos.')}};
$('passwordForm').onsubmit=async e=>{e.preventDefault();try{await rpc('apoyo_cambiar_password',{p_token:session,p_password:$('passwordNueva').value});$('passwordEstado').textContent='Contraseña actualizada.';e.target.reset()}catch{$('passwordEstado').textContent='No se pudo cambiar.'}};
$('paymentForm').onsubmit=async e=>{e.preventDefault();const pe=validatePayment('p');if(pe){$('paymentEstado').textContent=pe;return}try{await rpc('apoyo_guardar_pago',{p_token:session,p_pago:paymentData('p')});$('paymentEstado').textContent='Datos de pago actualizados.';await loadCuenta()}catch(err){console.error(err);$('paymentEstado').textContent='No se pudo guardar. '+(err.message||'')}};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tabview').forEach(x=>x.classList.add('hidden'));$('tab-'+(b.dataset.tab||b.dataset.adminTab)).classList.remove('hidden')});
async function loadAll(){await Promise.all([loadMensajes(),loadPagos(),loadCuenta(),me.es_admin?loadAsesores():Promise.resolve(),me.es_admin?loadSolicitudesAsesor():Promise.resolve(),me.es_admin?loadTodosMensajes():Promise.resolve(),me.es_admin?loadPapelera():Promise.resolve(),me.es_admin?loadEstadisticas():Promise.resolve()]);actualizarPendientes()}
async function loadMensajes(){const rows=await rpc('apoyo_mensajes',{p_token:session});$('mensajes').innerHTML=rows.length?rows.map(r=>`<div class="case"><div class="case-head"><strong>${esc(r.folio)}</strong><span class="pill">${esc(r.estado||'pendiente')}</span></div><p><b>Fecha:</b> ${fmtDate(r.creado)} · <b>País:</b> ${esc(r.pais||'No indicado')}</p><p><b>Nombre:</b> ${esc(r.nombre)}</p><p><b>Motivo:</b> ${esc(r.motivos)}</p><p>${esc(r.mensaje)}</p>${r.respuesta?`<div class="paybox"><b>Respuesta enviada:</b><p>${esc(r.respuesta)}</p></div>`:`<textarea id="resp-${r.id}" placeholder="Escribe aquí la respuesta..."></textarea><button class="btn" onclick="responder('${r.id}')">Enviar respuesta</button>`}</div>`).join(''):'<p>No hay mensajes asignados pendientes.</p>'}
window.responder=async id=>{const t=$('resp-'+id);if(!t.value.trim())return;await rpc('apoyo_responder',{p_token:session,p_id:id,p_respuesta:t.value.trim()});await loadAll()};
async function loadPagos(){const rows=await rpc('apoyo_pagos',{p_token:session});$('pagosTitulo').textContent=me.es_admin?'Pagos semanales de asesores':'Mis pagos semanales';$('pagos').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>Asesor</th><th>Semana</th><th>Mensajes</th><th>Importe</th><th>Estado</th><th>Pago</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.asesor}</td><td>${esc(r.semana)}</td><td>${r.mensajes}</td><td>$${Number(r.importe).toFixed(2)}</td><td>${esc(r.estado)}</td><td>${me.es_admin&&r.estado!=='pagado'?`<button class="mini-btn" onclick="marcarPagado('${r.id}')">Marcar pagado</button>`:(r.fecha_pago?new Date(r.fecha_pago).toLocaleDateString():'—')}</td></tr>`).join('')}</tbody></table></div>`:'<p>Aún no hay cortes semanales registrados.</p>'}
window.marcarPagado=async id=>{const ref=prompt('Referencia o nota del pago (opcional):')||'';await rpc('apoyo_marcar_pagado',{p_token:session,p_id:id,p_referencia:ref});await loadPagos()};
async function loadCuenta(){const d=await rpc('apoyo_datos_pago',{p_token:session});if(d)fillPayment('p',d)}
async function loadAsesores(){const rows=await rpc('apoyo_lista_asesores',{p_token:session});$('asesoresAdmin').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Asesor</th><th>Estado</th><th>Pago</th><th>Última actualización</th><th>Acceso</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.numero}</td><td>${r.activo?'Activo':'Inactivo'}</td><td>${r.metodo?`${esc(r.metodo)} · <button class="mini-btn" onclick="verPago(${r.numero})">Ver datos</button>`:'Sin registrar'}</td><td>${r.pago_actualizado?new Date(r.pago_actualizado).toLocaleString():'—'}</td><td>${r.numero===1000?'Administradora':`<button class="mini-btn danger" onclick="resetAcceso(${r.numero})">Restablecer acceso</button>`}</td></tr>`).join('')}</tbody></table></div>`}
window.verPago=async n=>{const d=await rpc('apoyo_admin_datos_pago',{p_token:session,p_numero:n});alert(`Asesor ${n}\nMétodo: ${d.metodo||'—'}\nTitular: ${d.titular||'—'}\nBanco: ${d.banco||'—'}\nCLABE: ${d.clabe||'—'}\nPayPal: ${d.paypal||'—'}`)};
window.resetAcceso=async n=>{if(!confirm(`¿Restablecer el acceso del asesor ${n}?`))return;const d=await rpc('apoyo_reset_password',{p_token:session,p_numero:n});alert(`Acceso restablecido. Contraseña temporal: ${d.password_temporal}\nAl ingresar deberá cambiarla.`);await loadAsesores()};

async function loadSolicitudesAsesor(){const rows=await rpc('apoyo_lista_solicitudes_asesor',{p_token:session});$('solicitudesAsesor').innerHTML=rows.length?rows.map(r=>`<div class="case"><div class="case-head"><strong>${esc(r.nombre)}</strong><span class="pill">${esc(r.estado)}</span></div><p><b>Correo:</b> ${esc(r.correo)}</p><p><b>Teléfono:</b> ${esc(r.telefono||'—')}</p><p><b>Motivo:</b> ${esc(r.motivo)}</p><p><b>Fecha:</b> ${new Date(r.creado).toLocaleString()}</p>${r.estado==='pendiente'?`<button class="mini-btn" onclick="aceptarSolicitud('${r.id}')">Aceptar y asignar cuenta</button> <button class="mini-btn danger" onclick="rechazarSolicitud('${r.id}')">No aceptar</button>`:(r.numero_asignado?`<div class="paybox"><b>Cuenta asignada:</b> Asesor ${r.numero_asignado}</div>`:'')}</div>`).join(''):'<p>No hay solicitudes para ser asesor.</p>'}
window.aceptarSolicitud=async id=>{if(!confirm('¿Aceptar esta solicitud y asignarle una cuenta de asesor disponible?'))return;try{const d=await rpc('apoyo_aceptar_solicitud_asesor',{p_token:session,p_id:id});alert(`Solicitud aceptada.\nNúmero de asesor: ${d.numero}\nContraseña inicial: ${d.password_temporal}\nComunica estos datos de forma privada a la persona.`);await loadAll()}catch(e){alert('No hay cuentas disponibles o no fue posible aceptar la solicitud.')}};
window.rechazarSolicitud=async id=>{if(!confirm('¿Marcar esta solicitud como no aceptada?'))return;await rpc('apoyo_rechazar_solicitud_asesor',{p_token:session,p_id:id});await loadSolicitudesAsesor()};


async function actualizarPendientes(){try{const rows=await rpc('apoyo_mensajes',{p_token:session});const n=rows.filter(r=>(r.estado||'pendiente')==='pendiente'&&!r.respuesta).length;const b=$('pendientesBadge');if(b){b.textContent=n;b.classList.toggle('hidden',n===0)}}catch(e){}}
function fmtDate(v){if(!v)return '—';try{return new Date(v).toLocaleString('es-MX')}catch{return v}}
function asesorSelect(current){let o='';for(let n=1010;n<=1200;n+=10)o+=`<option value="${n}" ${Number(current)===n?'selected':''}>${n}</option>`;return `<select id="asig-${current}-${Math.random().toString(36).slice(2)}" data-current="${current}">${o}</select>`}
async function loadTodosMensajes(){const rows=await rpc('apoyo_admin_todos_mensajes',{p_token:session});$('todosMensajes').innerHTML=rows.length?rows.map(r=>adminMessageCard(r,false)).join(''):'<p>No hay mensajes.</p>'}
async function loadPapelera(){const rows=await rpc('apoyo_admin_papelera',{p_token:session});$('papeleraMensajes').innerHTML=rows.length?rows.map(r=>adminMessageCard(r,true)).join(''):'<p>La Papelera está vacía.</p>'}
function adminMessageCard(r,inTrash){return `<div class="case"><div class="case-head"><strong>${esc(r.folio)}</strong><span class="pill">${esc(r.estado||'pendiente')}</span></div><p><b>Fecha:</b> ${fmtDate(r.creado)} · <b>País:</b> ${esc(r.pais||'No indicado')} · <b>Asesor:</b> ${esc(r.asesor||'—')}</p><p><b>Nombre:</b> ${esc(r.nombre)} · <b>Correo:</b> ${esc(r.correo||'—')}</p><p><b>Motivo:</b> ${esc(r.motivos||'')}</p><p>${esc(r.mensaje||'')}</p>${r.respuesta?`<div class="paybox"><b>Respuesta:</b><p>${esc(r.respuesta)}</p></div>`:''}<div class="admin-actions">${inTrash?`<button class="mini-btn" onclick="restaurarMensaje('${r.id}')">Restaurar</button><button class="mini-btn danger" onclick="eliminarDefinitivo('${r.id}')">Eliminar definitivamente</button>`:`<select id="reasig-${r.id}">${Array.from({length:20},(_,i)=>1010+i*10).map(n=>`<option value="${n}" ${Number(r.asesor)===n?'selected':''}>Asesor ${n}</option>`).join('')}</select><button class="mini-btn" onclick="reasignarMensaje('${r.id}')">Reasignar</button><button class="mini-btn" onclick="cambiarEstado('${r.id}','pendiente')">Pendiente</button><button class="mini-btn" onclick="cambiarEstado('${r.id}','atendido')">Atendido</button><button class="mini-btn danger" onclick="papeleraMensaje('${r.id}')">Papelera</button>`}</div></div>`}
window.reasignarMensaje=async id=>{const n=Number($('reasig-'+id).value);await rpc('apoyo_admin_reasignar',{p_token:session,p_id:id,p_asesor:n});await loadAll()};
window.cambiarEstado=async(id,estado)=>{await rpc('apoyo_admin_estado',{p_token:session,p_id:id,p_estado:estado});await loadAll()};
window.papeleraMensaje=async id=>{if(!confirm('¿Enviar este mensaje a la Papelera?'))return;await rpc('apoyo_admin_mover_papelera',{p_token:session,p_id:id});await loadAll()};
window.restaurarMensaje=async id=>{await rpc('apoyo_admin_restaurar',{p_token:session,p_id:id});await loadAll()};
window.eliminarDefinitivo=async id=>{if(!confirm('Esta acción eliminará definitivamente el mensaje. ¿Continuar?'))return;await rpc('apoyo_admin_eliminar_definitivo',{p_token:session,p_id:id});await loadAll()};
async function loadEstadisticas(){const d=await rpc('apoyo_estadisticas',{p_token:session});const totals=d.totales||{};const months=d.meses||[];const countries=d.paises||[];const maxM=Math.max(1,...months.map(x=>Number(x.total)||0));const maxC=Math.max(1,...countries.map(x=>Number(x.total)||0));$('estadisticas').innerHTML=`<div class="stats-grid"><div class="stat-card"><span>Total histórico</span><strong>${totals.total||0}</strong></div><div class="stat-card"><span>Este mes</span><strong>${totals.mes_actual||0}</strong></div><div class="stat-card"><span>Pendientes</span><strong>${totals.pendientes||0}</strong></div><div class="stat-card"><span>Atendidos</span><strong>${totals.atendidos||0}</strong></div></div><h3>Mensajes por mes</h3>${months.map(x=>bar(x.periodo,x.total,maxM)).join('')||'<p>Sin datos.</p>'}<h3>Mensajes por país</h3>${countries.map(x=>bar(x.pais||'No indicado',x.total,maxC)).join('')||'<p>Sin datos.</p>'}`}
function bar(label,val,max){const pct=Math.round((Number(val)||0)*100/max);return `<div class="bar-row"><span>${esc(label)}</span><div class="bar-track"><div class="bar-fill" style="width:${pct}%"></div></div><strong>${Number(val)||0}</strong></div>`}

function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
init();